//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospitals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time
    {
        public int TimeId { get; set; }
        public Nullable<System.TimeSpan> Time1 { get; set; }
    }
}
